-- Create a table for student payments
CREATE TABLE payments (
  id bigint generated by default as identity primary key,
  group_id bigint references student_groups(id) on delete cascade,
  
  -- Auto-filled Snapshot Data (for record keeping even if group changes)
  group_name text,
  members text, -- Stored as comma-separated string or JSON
  program text,
  year_level text,
  section text,
  adviser text,
  panels text, -- Stored as comma-separated string or JSON
  
  -- Submission Data
  receipt_url text, -- Link to the uploaded image
  amount numeric(10,2), -- Just in case, though not explicitly asked, usually good to have
  status text default 'Pending', -- Pending, Verified, Rejected
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table payments enable row level security;

-- Policies
create policy "Enable all access for all users" on payments for all using (true);
