-- Run this in your Supabase SQL Editor to set up the tables for Instructor/Student Groups

-- 1. Table for Student Groups (The account entity)
CREATE TABLE student_groups (
  id bigint generated by default as identity primary key,
  group_name text not null,
  password text not null,
  program text,
  year_level text,
  section text,
  adviser text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table for Individual Students (Members of the group)
-- This allows you to grade them individually later
CREATE TABLE students (
  id bigint generated by default as identity primary key,
  group_id bigint references student_groups(id) on delete cascade,
  full_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. (Optional) Row Level Security Policies
-- Enable RLS
alter table student_groups enable row level security;
alter table students enable row level security;

-- Allow public access for now (or restrict as needed)
create policy "Enable all access for all users" on student_groups for all using (true);
create policy "Enable all access for all users" on students for all using (true);
