
-- 1. Create a new table for defense remarks and statuses
CREATE TABLE defense_statuses (
    id bigint generated by default as identity primary key,
    group_id bigint references student_groups(id) on delete cascade,
    defense_type text not null, -- 'Title Defense', 'Pre-Oral Defense', 'Final Defense'
    
    -- Store statuses as JSON (e.g., {"title1": "Approved", "title2": "Rejected"})
    statuses jsonb default '{}'::jsonb,
    
    -- Store remarks as JSON (e.g., {"title1": "Good job", "title2": "Needs work"})
    remarks jsonb default '{}'::jsonb,
    
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Migrate existing data (Optional, if you want to keep old data)
-- INSERT INTO defense_statuses (group_id, defense_type, statuses, remarks)
-- SELECT id, 'Title Defense', title_status::jsonb, title_remarks::jsonb FROM student_groups WHERE title_status IS NOT NULL;

-- 3. Disable RLS for this new table to avoid permission issues
ALTER TABLE defense_statuses DISABLE ROW LEVEL SECURITY;
