-- Run this in your Supabase SQL Editor to set up the tables for Schedules and Grades

-- 1. Table for Schedules (Defenses)
CREATE TABLE schedules (
  id bigint generated by default as identity primary key,
  group_id bigint references student_groups(id) on delete cascade unique, -- One schedule per group for now
  panel1 text,
  panel2 text,
  panel3 text,
  panel4 text,
  panel5 text,
  program_head text,
  chairman text,
  schedule_date date,
  schedule_time time, -- Optional, if you want specific time
  status text default 'Pending', -- Pending, Completed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Table for Grades
-- This stores individual grades for students
CREATE TABLE grades (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  schedule_id bigint references schedules(id) on delete cascade,
  
  -- Individual Criteria (Example based heavily on Capstone grading standards)
  -- You can adjust these columns
  proposal_grade numeric(5,2),
  oral_defense_grade numeric(5,2),
  document_grade numeric(5,2),
  
  final_grade numeric(5,2),
  remarks text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table schedules enable row level security;
alter table grades enable row level security;

-- Policies
create policy "Enable all access for all users" on schedules for all using (true);
create policy "Enable all access for all users" on grades for all using (true);
