-- Run this in your Supabase SQL Editor

-- 1. Create the table for storing PDF annotations
create table if not exists pdf_annotations (
  id bigint generated by default as identity primary key,
  group_id bigint not null,
  file_key text not null,
  annotation_data jsonb,
  user_name text,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  
  -- Critical: This ensures each file has only ONE annotation record
  constraint pdf_annotations_group_file_unique unique (group_id, file_key)
);

-- 2. Enable Row Level Security (RLS)
alter table pdf_annotations enable row level security;

-- 3. Create Policy: Allow anyone to read annotations
create policy "Public Read"
  on pdf_annotations for select
  using ( true );

-- 4. Create Policy: Allow anyone to insert/update annotations
-- (In a real app, you might restrict this to logged-in users, but for now we want to ensure it works)
create policy "Public Insert"
  on pdf_annotations for insert
  with check ( true );

create policy "Public Update"
  on pdf_annotations for update
  using ( true );
