
-- SQL Code to create the accounts table
CREATE TABLE accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  password text not null,
  role text not null,
  designation text
);
