-- Run this to update your existing 'schedules' table
-- 1. Remove unnecessary columns
ALTER TABLE schedules 
DROP COLUMN IF EXISTS program_head,
DROP COLUMN IF EXISTS chairman;

-- 2. Add Venue column (Time already exists in previous schema, but ensuring it's there)
ALTER TABLE schedules 
ADD COLUMN IF NOT EXISTS schedule_venue text;

-- (Optional) If you didn't create the table yet, use the updated Full Schema below:
/*
CREATE TABLE schedules (
  id bigint generated by default as identity primary key,
  group_id bigint references student_groups(id) on delete cascade unique,
  panel1 text,
  panel2 text,
  panel3 text,
  panel4 text,
  panel5 text,
  schedule_date date,
  schedule_time time,
  schedule_venue text,
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
*/
